### ISSUE TITLE
Breakpoints are not hit

### ISSUE THREAD

**Issue by Deilan** [EnterpriseJSTutorial/vscode-ts-node-debugging#1]
- VS Code Version: 1.12.2
- OS Version: Windows 8.1 x64
- Node.js Version: 7.10.0

Cloned the repo, installed the packages, launched `Current TS File` configuration -> Breakpoints are not hit when a file is open, neither when it's not currently open.

**Comment by dupski** [comment]
Hi @Deilan , could you try setting a breakpoint on one of the expect() statements in the __tests__ folder and see if that gets hit? (with the 'Current TS Tests File' debug option)

The 'Current TS File' debug option was working for me in node 6.10.1, but appears to not work in 6.10.3 and 7.x :(

**Comment by dupski** [comment]
I've just pushed a small update that gets the mocha test breakpoints working in Node 7 and VS Code 1.12.2 on ubuntu. I don't have a windows machine to test unfortunately.

I've added a note to the readme that the "Current TS File" launch task is not currently working - if anyone finds a fix for this please let me know!
