### ISSUE TITLE
Ability to use with docker

### ISSUE THREAD

**Issue by montera82** [EnterpriseJSTutorial/vscode-ts-node-debugging#11]
i wonder how i could make it work with a dockerfile like this

FROM node:9-alpine

ARG APP=/http

WORKDIR ${APP}

COPY . ${APP}/

RUN npm install

RUN npm i -g typescript ts-node knex@0.15.2

EXPOSE 3000

RUN npm run debug

**Comment by dupski** [comment]
Hi @montera82 , unfortunately this is not something I will be looking into but feel free to submit a PR if you get it working! :)
