### ISSUE TITLE
Whoa, cool. Happen to know how this would work with jest?

### ISSUE THREAD

**Issue by matt-erhart** [EnterpriseJSTutorial/vscode-ts-node-debugging#6]
Or other test runners in general? I'll look into myself, but it'd be great if you had an easy answer. Thanks!

**Comment by dupski** [comment]
Hey Matt, we use Jest at work and so far I've not been able to get it to work with VS Code debugging unfortunately. Jest (and ts-jest) does some weird things with source maps and node processes that I've not managed to figure out.

Be keen to know if anyone has a solution though! :)
